/*
 * This file is generated by jOOQ.
 */
package vi.al.ro.model.db;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import vi.al.ro.model.db.tables.KeyStore;
import vi.al.ro.model.db.tables.records.KeyStoreRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<KeyStoreRecord> CONSTRAINT_9 = Internal.createUniqueKey(KeyStore.KEY_STORE, DSL.name("CONSTRAINT_9"), new TableField[] { KeyStore.KEY_STORE.ID }, true);
    public static final UniqueKey<KeyStoreRecord> CONSTRAINT_9D = Internal.createUniqueKey(KeyStore.KEY_STORE, DSL.name("CONSTRAINT_9D"), new TableField[] { KeyStore.KEY_STORE.PATH_FILE }, true);
}
