/*
 * This file is generated by jOOQ.
 */
package vi.al.ro.model.db;


import vi.al.ro.model.db.tables.KeyStore;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.key_store</code>.
     */
    public static final KeyStore KEY_STORE = KeyStore.KEY_STORE;
}
